---
common_extra_packages: []
common_update_apt_cache: true
common_create_workdirs: true
common_enable_rsyslog_service: true
common_manage_base_packages: true
common_manage_base_dirs: true
common_manage_rsyslog: true

project_owner: "user1"
project_group: "user1"

common_packages:
  - vim
  - nano
  - curl
  - wget
  - git
  - unzip
  - zip
  - jq
  - tree
  - rsync
  - bash-completion
  - ca-certificates
  - gnupg
  - python3
  - python3-pip
  - sudo
  - acl
  - rsyslog

common_directories:
  - "/opt/ansible-db-secure"
  - "/opt/ansible-db-secure/reports"
  - "/opt/ansible-db-secure/tmp"
